//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSedima.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int IdEmpleado { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime FecRegistro { get; set; }
    }
}
