//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSedima.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES
    {
        public int IdReporte { get; set; }
        public string Cliente { get; set; }
        public string Caldera { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime FecRegistro { get; set; }
        public string FA { get; set; }
        public string FG { get; set; }
        public string PC { get; set; }
        public string ABN { get; set; }
        public string ANN { get; set; }
        public string VN { get; set; }
        public string FCN { get; set; }
        public string PF { get; set; }
        public string PDC { get; set; }
        public string MC { get; set; }
        public string VV { get; set; }
        public string VG { get; set; }
        public string BG { get; set; }
        public string PI { get; set; }
        public string EFP { get; set; }
        public string FF { get; set; }
        public string BNA { get; set; }
        public string CPV { get; set; }
        public string LQ { get; set; }
        public string CE { get; set; }
        public string Chimenea { get; set; }
        public string Agua_tanque { get; set; }
        public string EC { get; set; }
        public string SC { get; set; }
        public string VAP { get; set; }
        public string AA { get; set; }
        public string AC { get; set; }
        public string BAA { get; set; }
        public string BAD { get; set; }
        public string MV { get; set; }
        public string Min_Co2 { get; set; }
        public string Min_O2 { get; set; }
        public string Min_Ppm { get; set; }
        public string Min_Ex_Aire { get; set; }
        public string Med_Co2 { get; set; }
        public string Med_O2 { get; set; }
        public string Med_Ppm { get; set; }
        public string Med_Ex_Aire { get; set; }
        public string Max_Co2 { get; set; }
        public string Max_O2 { get; set; }
        public string Max_Ppm { get; set; }
        public string Max_Ex_Aire { get; set; }
        public string Comentarios { get; set; }
        public string STATUS { get; set; }
        public string ARR { get; set; }
        public string VOLTS { get; set; }
    }
}
